### ISSUE TITLE
v2.0.0 Tracking Issue

### ISSUE THREAD

**Issue by andrewbranch** [andrewbranch/gatsby-remark-vscode#64]
Short version: several things are necessitating some breaking changes, and it’s a good opportunity to think about what else I would want to see in a v2. I haven’t gone into the details much here, but thoughts and questions are welcome.

WIP in the [v2 branch](https://github.com/andrewbranch/gatsby-remark-vscode/tree/v2). **You can try it out now!** `npm install gatsby-remark-vscode@alpha`

## Meta/infrastructure
- [x] Publish alpha releases from v2 branch (#65)
- [ ] Improved integration test infrastructure
- [x] Add migration guide, contributing guide, COC, etc.
- [x] Infrastructure for marking options as deprecated

## Breaking changes
- [x] Breaking changes to token CSS/HTML to fix multi-theme conflicts (#63)
- [x] Replace extension downloading capability with extension retrieval from node_modules (#67)

## Stable features
- [x] Parent-selector-based theme switching (#39, #66)
- [ ] ~~Replace oniguruma with onigasm by default, use oniguruma if available (#22, #24)~~ (vscode-textmate has a hard dependency on oniguruma)

## Preview features
(Hoping to make stable for 2.1)
- [x] Populate GraphQL with tokenization data (#59, #53)
