### ISSUE TITLE
v3 Tracking Issue

### ISSUE THREAD

**Issue by andrewbranch** [andrewbranch/gatsby-remark-vscode#96]
There’s now enough momentum behind a few breaking changes that it’s time to start putting together a v3 branch! Progress in the v3 branch is being published to npm under `gatsby-remark-vscode@alpha`. Here’s the plan:

## New features!

- [x] Line transformers can contribute gutter cells - #95
- [x] Option to show line numbers (enabled by gutter cells) - #28, #95
- [x] Diff highlighting courtesy of @janosh (enabled by gutter cells) - #62, #88 

## Private APIs becoming public!

These need docs, tests, and final API refinements.

- [ ] Line transformers
- [ ] GraphQL resolvers

## Old APIs becoming deprecated!

This needs to be documented in MIGRATING.md.

- [x] `CodeBlockData['codeFenceNode']` (succeeded by `node` in #89)

## Deprecated APIs being removed!

- [x] Old `colorTheme` option

## Improvements!

- [x] Make the default CSS variables better - #51, #106 

## Not a blocker for v3 but nice to have

- [ ] Better logging/tracing - #91 
- [ ] Allow highlighting to be disabled for some code blocks - #79 
- [ ] Docs site with examples - #36 
- [ ] CLI to show info about extensions, languages, and themes - #90

**Comment by andrewbranch** [comment]
Update: I'm behind on the schedule I was hoping for here and I really want to make a good docs site, but it’s a lot of work, and SemVer-wise it’s not a blocker. I’m going to defer the things that aren’t strictly needed for SemVer.
